sudo: required
services:
  - docker

before_install:
  - docker build -t apatil3/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true apatil3/react-test npm test -- --coverage 

after_success:
  - docker build -t apatil3/multi-client ./client
  - docker build -t apatil3/multi-nginx  ./nginx
  - docker build -t apatil3/multi-server ./server
  - docker build -t apatil3/multi-worker ./worker

  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images
  - docker push apatil3/multi-client
  - docker push apatil3/multi-nginx
  - docker push apatil3/multi-server
  - docker push apatil3/multi-worker

  # deploy section 
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-423951603323
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY_MULTI"
  secret_access_key:
    secure: "$AWS_SECRET_KEY_MULTI"

